async () => {
  const results = [], wait = () => new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r)));
  const check = (ok, label) => { if (!ok) throw Error(label); results.push(label); };
  const searchFor = key => document.querySelector(`[data-vui-search-input="${key}"]`);
  const type = (input, text) => { input.focus(); input.value = text; input.dispatchEvent(new InputEvent('input', { bubbles: true })); };
  const shown = (list, selector) => [...list.querySelectorAll(selector)].filter(row => !row.classList.contains('vui-search-hidden'));
  state.groups = Array.from({length: 12}, (_, i) => ({...createDefaultGroup('site'), id:'search-group-'+i, name:'Group '+i}));
  state.selectedGroupId = state.groups[0].id; render(); await wait();
  const multi = {...state.groups[0], scopes:['youtube','reddit','twitter','bilibili','facebook','instagram'].map((platform,i)=>({id:'items-'+i,surface:'items',platform,action:'hide',when:{kind:'all'}}))};
  renderGroupScopes(multi, true);await wait();
  type(searchFor('vault-scopes'), 'reddit');
  check(shown(groupScopesList, '.scope-chip').length===1 && multi.scopes.length===6,'target search filters existing scope tabs without removing policy lines');
  const groups = searchFor('vault-groups');
  check(groups && !groups.closest('.vui-search').hidden, 'six or more groups show search');
  type(groups, 'gROUP 11'); await wait();
  check(shown(groupList, '.group-card').length === 1 && state.groups.length === 12, 'group search ignores case and preserves the full order');
  groups.setSelectionRange(1, 4); renderGroupList(); await wait();
  check(document.activeElement === groups && groups.value === 'gROUP 11' && groups.selectionStart === 1, 'group updates preserve search query, caret and focus');
  shown(groupList, '.group-card')[0].click(); await wait();
  check(state.selectedGroupId === 'search-group-11', 'filtered group opens its original identity');
  type(groups, '');
  blockedSitesField.value = Array.from({length: 6}, (_,i) => 'host'+i+'.example').join('\n'); renderBlockedSites(); await wait();
  const sites = searchFor('vault-sites'), original = blockedSitesField.value;
  type(sites, 'HOST5'); await wait();
  check(shown(blockedSitesList, '.site-chip').length === 1 && blockedSitesField.value === original, 'saved websites filter without changing their data');
  check(blockedSitesList.querySelector('.site-chip-add').getClientRects().length > 0, 'add control stays available during filtering');
  type(sites, 'no-such-site');
  check(!sites.closest('.vui-search').querySelector('.vui-search-empty').hidden, 'no matches is explicit');
  blockedSitesField.value = 'tiny.example'; renderBlockedSites(); await wait();
  check(!sites.closest('.vui-search').hidden, 'active query survives a list shrinking below the cutoff');
  sites.closest('.vui-search').querySelector('.vui-search-clear').click();
  check(sites.closest('.vui-search').hidden && shown(blockedSitesList, '.site-chip').length === 1, 'clear restores entries and hides short-list search');
  blockedSitesField.value = Array.from({length: 5}, (_,i) => 'host'+i+'.example').join('\n'); renderBlockedSites(); await wait();
  check(sites.closest('.vui-search').hidden, 'exactly five entries need no search');
  blockedAppsData.value = JSON.stringify(Array.from({length:6},(_,i)=>({id:'com.bundle.'+i,name:'App '+i}))); renderBlockedApps(); await wait();
  type(searchFor('vault-apps'), 'bundle.5');
  check(shown(blockedAppsList, '.app-chip').length === 1, 'saved apps can be found by identifier');
  platformAuthorsField.value = Array.from({length:6},(_,i)=>'@creator'+i).join('\n'); refreshChipField(platformAuthorsField); await wait();
  type(searchFor('vault-chips:'+platformAuthorsField.id), 'CREATOR5');
  check(shown(document.querySelector('[data-vui-search="vault-chips:'+platformAuthorsField.id+'"]'), '.entry-chip').length === 1, 'saved creator filters are searchable');
  platformTagsField.value = Array.from({length:6},(_,i)=>'Topic '+i+'@3').join('\n'); await wait();
  const find = platformTagsField.previousElementSibling, beforeRules = platformTagsField.value;
  type(find.querySelector('input'), 'topic 5');
  check(!find.hidden && platformTagsField.value === beforeRules && platformTagsField.value.slice(platformTagsField.selectionStart,platformTagsField.selectionEnd)==='Topic 5@3', 'tag-rule Find locates the matching line without modifying syntax');
  logFeedGroupId = state.selectedGroupId;
  for (let i=0;i<6;i++) renderLogFeedEntry({id:'search-log-'+i,source:'v.log',groupId:logFeedGroupId,message:'Message '+i,timestamp:Date.now()});
  await wait(); type(searchFor('vault-logs'),'message 5');
  check(shown(logFeedList,'.log-feed-entry').length===1 && logFeedCount.textContent==='1','log search filters only the selected group and updates the visible count');
  const select = document.createElement('select'); select.id = 'search-option-fixture';
  const group = document.createElement('optgroup'); group.label='Providers';
  for(let i=0;i<8;i++){const option=document.createElement('option');option.value='value-'+i;option.textContent='Provider '+i;option.disabled=i===7;group.appendChild(option);}
  select.appendChild(group);document.body.appendChild(select);VaultUI.enhance(select);
  let changes=0;select.addEventListener('change',()=>changes++);
  select.nextElementSibling.querySelector('button').click();await wait();
  const menu=document.querySelector('.vui-menu'), query=menu.querySelector('input');
  type(query,'provider 6');
  check(menu.querySelectorAll('.vui-menu-item').length===1 && menu.querySelector('.vui-menu-group').textContent==='Providers' && select.value==='value-0', 'dropdown search retains optgroups and does not change selection');
  select.value='value-2';await wait();
  check(menu.querySelector('input')===query && query.value==='provider 6' && document.activeElement===query,'option updates preserve dropdown query and focus');
  menu.querySelector('.vui-menu-item').click();
  check(select.value==='value-6' && changes===1 && !document.querySelector('.vui-menu'), 'filtered dropdown chooses the original option through one change event');
  select.nextElementSibling.querySelector('button').click();await wait();type(document.querySelector('.vui-menu input'),'provider 7');
  check(document.querySelector('.vui-menu-item').disabled,'disabled results remain disabled');VaultUI.close();
  select.remove();
  if (globalThis.chrome && chrome.runtime) check(true, 'production editor runs with actual extension APIs');
  return results;
}

