#!/usr/bin/env python3
"""Generate the compact content-world catalogs from the canonical UI catalogs."""
import json
from pathlib import Path
root = Path(__file__).resolve().parents[1]
messages = {}
for source in sorted((root / "translation").glob("*.json")):
    catalog = json.loads(source.read_text())
    messages[source.stem] = {key: value for key, value in catalog.items() if key.startswith(("contentTag.", "contentPage."))}
(root / "content-messages.js").write_text("// Generated by scripts/build-content-messages.py; edit translation/*.json.\n"
    + "globalThis.VaultContentMessages = " + json.dumps(messages, ensure_ascii=False, separators=(",", ":")) + ";\n")
